title: CODI
description: Programa CODI - IES Benigasló
theme: just-the-docs

url: https://jaume-av.github.io/CODI/

aux_links:
  "Accés a Programa CODI":
    - https://www.formacioncodi.gob.es/login/index.php

search_enabled: true

footer:
  copyright: "© 2024 Gómez - Aragó"
  links:
    - title: "Llicència CC BY-SA 4.0"
      url: "https://creativecommons.org/licenses/by-sa/4.0/"

# Navegació directa sense desplegables
collections:
  docs:
    output: true
    permalink: /:path/